name: Generate Doxygen documentation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      - name: Generate Doxygen documentation
        run: doxygen ./Documentation/Doxyfile
      - name: Create documentation branch
        run: git branch documentation
      - name: Checkout documentation branch
        run: git checkout documentation
      - name: Configure stuff
        run: |
        git config --global user.name "Actions"
        git config --global user.email "you@example.com"
      - name: Add changes
        run: git add -A
      - name: Commit changes
        run: git commit -m "Updated Doxygen documentation"
      - name: Push changes
        run: git push origin documentation