name: Generate Doxygen documentation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      - name: Generate Doxygen documentation
        run: doxygen ./Documentation/Doxyfile
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'