name: Generate Doxygen documentation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Doxygen
        run: |
          apt-get update
          apt-get install -y doxygen
      - name: Generate Doxygen documentation
        run: doxygen ../../Documentation/Doxyfile
