name: Generate Doxygen documentation
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      - name: Current Directory
        run: ls
