name: Doxygen deployment

on:
  # Runs on pushes targeting the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen
      - name: Generate Doxygen documentation
        run: doxygen ./Documentation/Doxyfile
      - name: Configure User Name
        run: git config --global user.name "Actions"
      - name: Configure Email
        run: git config --global user.email "you@example.com"
      - name: Create documentation branch
        run: git branch documentation
      - name: Checkout documentation branch
        run: git checkout documentation
      - name: Add changes
        run: git add -A
      - name: Commit changes
        run: git commit -m "Updated Doxygen documentation"
      - name: Push changes
        run: git push origin documentation
